-- 코드를 입력하세요
SELECT date_format(N.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT FROM ONLINE_SALE AS N
WHERE SALES_DATE LIKE '2022-03%'
UNION ALL
SELECT date_format(F.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, F.PRODUCT_ID, NULL, F.SALES_AMOUNT FROM OFFLINE_SALE AS F
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC;