-- 코드를 입력하세요
SELECT U.TITLE, U.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, date_format(R.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD AS U
INNER JOIN USED_GOODS_REPLY AS R
ON U.BOARD_ID = R.BOARD_ID
WHERE U.CREATED_DATE LIKE '2022-10%'
ORDER BY R.CREATED_DATE ASC, U.TITLE ASC;