-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE FROM REST_INFO AS I
RIGHT JOIN REST_REVIEW AS R
ON I.REST_ID = R.REST_ID
GROUP BY I.REST_ID HAVING I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, I.FAVORITES DESC;